spring:
  application:
    name: service-discovery-eureka
server:
  port: 8761

  sleuth:
    sampler:
      probability: 1.0 #100%

## Eureka server discovery
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka


