---
server:
  port: 9999
spring:
  application:
    name: ms-customer-rater-credit
  feign:
    client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 10000
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  sleuth:
    sampler:
      probability: 1.0 #100%

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true

mq:
  queues:
    issuance_of_cards: issuance_of_cards

management:
  endpoints:
    web:
      exposure:
        include:
          - '*'

logging:
    file:
      name: ./logs/log-file.log