---
server:
  port: 9999
spring:
  application:
    name: ms-customer-rater-credit
  feign:
    client:
      config:
        default:
          connectTimeout: 60000
          readTimeout: 10000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    enabled: true
