---
name: Continuous Integration with Github
on:
  push:
    branches:
      - master
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Login to dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
         
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: '17'
      
      - name: Create Image - Service Discovery
        working-directory: ./service-discovery
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Create Image - Service Discovery jar
        working-directory: ./service-discovery
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build - Service Discovery
        working-directory: ./service-discovery
        run: docker-compose build
        
      - name: Create Image - Gateway
        working-directory: ./gateway
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Create Image - Gateway jar
        working-directory: ./gateway
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build - Gateway
        working-directory: ./gateway
        run: docker-compose build
        
      - name: Create Image - Cards
        working-directory: ./ms-cards
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Create Image - Cards jar
        working-directory: ./ms-cards
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build - Cards
        working-directory: ./ms-cards
        run: docker-compose build
        
      - name: Create Image - Customer
        working-directory: ./ms-customer
        run: mvn spring-boot:build-image -DskipTests
      
      - name: Create Image - Customer jar
        working-directory: ./ms-customer
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build - Customer
        working-directory: ./ms-customer
        run: docker-compose build
        
      - name: Push to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_USERNAME }}/service-discovery:0.0.1 ${{ secrets.DOCKER_USERNAME }}/service-discovery:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/service-discovery:0.0.1 ${{ secrets.DOCKER_USERNAME }}/service-discovery:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1 ${{ secrets.DOCKER_USERNAME }}/gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/gateway:0.0.1 ${{ secrets.DOCKER_USERNAME }}/gateway:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-cards:0.0.1 ${{ secrets.DOCKER_USERNAME }}/ms-cards:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-cards:0.0.1 ${{ secrets.DOCKER_USERNAME }}/ms-cards:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-customer:0.0.1 ${{ secrets.DOCKER_USERNAME }}/ms-customer:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/ms-customer:0.0.1 ${{ secrets.DOCKER_USERNAME }}/ms-customer:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/service-discovery:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/service-discovery:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-cards:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-cards:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-customer:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/ms-customer:latest
