---
name: Continuous Integration with Github
on:
  push:
    branches:
      - master
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Login to dockerhub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Create Image Service Discovery
      - uses: docker/build-push-action@v4.0.0
        with:
          context: ./microservice-concepts-prateces/service-discovery
          file: ./microservice-concepts-prateces/service-discovery
          push: true
          tags:
            carlosbarbosafilho/service-discovery:v1
            carlosbarbosafilho/service-discovery:latest
